# 🤝 Apoie o Letrário

O **Letrário** é um projeto pessoal criado por mim, SARA — desenvolvedora em formação e leitora apaixonada.  
Ele nasceu como uma ferramenta para organizar os meus livros, e hoje está crescendo com carinho e propósito.

---

## 💡 Por que apoiar?

Se você acredita na leitura como forma de conexão e quer incentivar projetos independentes feitos por pessoas reais, seu apoio pode fazer toda a diferença.

Com sua ajuda, posso:

- Manter o projeto online e acessível
- Investir em melhorias e novas funcionalidades
- Aprender e crescer como desenvolvedora

---

## 🌱 Formas de apoio

- **Compartilhe** o Letrário com outras pessoas que amam livros
- **Contribua com ideias** ou feedbacks para melhorar o sistema
- **Doe** qualquer valor para ajudar nos custos de hospedagem e domínio

---

## 📬 Quer apoiar?

Você pode entrar em contato comigo pelo e-mail:  
**letrario.contato@gmail.com**

Ou me encontrar nas redes sociais:  
**[@sarasilva](https://www.linkedin.com/in/saravssilva/)** no LinkedIn

---

**Obrigada por acreditar em projetos pequenos com grandes sonhos.**  
*O Letrário é feito com código, café e muito amor pelos livros.*
